
<!-- https://developer.linkedin.com/plugins/follow-company : Get the data-id by entering the company name on the mentioned site 
and copy paste the codeprovided there. See to it that you add http: or https:  before //platform else the button will not appear.-->    
<script src="https://platform.linkedin.com/in.js" type="text/javascript">
    lang: en_US
</script>
<script type="IN/FollowCompany" data-id="166744" data-counter="right"></script>
